---

- name: "Create /var/awslogs/etc"
  file:
    path: /var/awslogs/etc
    state: directory
    mode: 755

- name: "Create /etc/awslogs"
  file:
    path: /etc/awslogs
    state: directory
    mode: 755

- name: "Make /var/awslogs/state/ directory"
  file:
    path: /var/awslogs/state/
    state: directory
    mode: 755

- name: "Set region for Cloudwatch endpoint"
  template:
    src: templates/etc/aws.conf.j2
    dest: /var/awslogs/etc/aws.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - restart awslogs

- name: "Drop the awslogs configuration file"
  template:
    src: templates/etc/awslogs/awslogs.conf.j2 
    dest: /var/awslogs/etc/awslogs.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - restart awslogs

- name: "Configure AWS CloudWatch Log Agent logging"
  template:
    src: etc/awslogs/awslogs.logging.conf.j2
    dest: /etc/awslogs/awslogs.logging.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart awslogs
  when: awslogs_loglevel != ""

