---

- name: "Make /var/awslogs/state/ directory"
  file:
    path: /var/awslogs/state/
    state: directory
    mode: 755

- name: "Configure AWS CloudWatch Log Agent logging"
  template:
    src: etc/awslogs/awslogs.logging.conf.j2
    dest: /etc/awslogs/awslogs.logging.conf
    owner: root
    group: root
    mode: 0644
  when: awslogs_loglevel != ""

