---

- name: "Create /etc/awslogs"
  file:
    path: /etc/awslogs
    state: directory
    mode: 755

- name: "Configure Cloudwatch Log Agent."
  include: "conf.yml"

- stat: path=/var/log/awslogs-agent-setup.log
  register: agent_setup_log

- name: "Install Cloudwatch Log Agent"
  include: "agent.yml"
  when:
    - agent_setup_log.stat.exists == False

- name: "Set region for Cloudwatch endpoint"
  template:
    src: templates/etc/aws.conf.j2
    dest: /etc/awslogs/awslogs.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - restart awslogs


